replication:
  connections:
    - type: postgresql
      uri: postgres://postgres:8248445802@database-1.cka0t20iwlxf.ap-south-1.rds.amazonaws.com:5432/live_db?sslmode=require
      publication_name: powersync

storage:
  type: mongodb
  uri: mongodb://mongo:27017/powersync_anderson?replicaSet=rs0

port: 8080

sync_rules:
  content: |
    bucket_definitions:
      global:
        data:
          - SELECT * FROM data.price_list WHERE visible = true

      technician_work_orders:
        parameters: SELECT request.jwt() ->> 'emp_id' AS emp_id
        data:
          - SELECT doc_id as id, tenant_id, hcpm_id, doc_id, patient_name,
              visit_date, visit_time, doctor_name, pro_id, manager_id,
              manager_name, assigned_id, assigned_to, b2b_client_id,
              b2b_client_name, status, server_status, bill_amount,
              received_amount, discount_amount, doc, bill_number, lab_number,
              visible, created_by, created_at, last_updated_by, last_updated_at,
              sync_window
            FROM data.hc_patient_visit_detail
            WHERE assigned_id = bucket.emp_id
              AND visible = true

      manager_work_orders:
        parameters: SELECT request.jwt() ->> 'tenant_id' AS tenant_id
        data:
          - SELECT doc_id as id, tenant_id, hcpm_id, doc_id, patient_name,
              visit_date, visit_time, doctor_name, pro_id, manager_id,
              manager_name, assigned_id, assigned_to, b2b_client_id,
              b2b_client_name, status, server_status, bill_amount,
              received_amount, discount_amount, doc, bill_number, lab_number,
              visible, created_by, created_at, last_updated_by, last_updated_at,
              sync_window
            FROM data.hc_patient_visit_detail
            WHERE tenant_id::text = bucket.tenant_id
              AND visible = true
              AND sync_window = true

      billing_work_orders:
        parameters: SELECT request.jwt() ->> 'tenant_id' AS tenant_id
        data:
          - SELECT doc_id as id, tenant_id, hcpm_id, doc_id, patient_name,
              visit_date, visit_time, doctor_name, pro_id, manager_id,
              manager_name, assigned_id, assigned_to, b2b_client_id,
              b2b_client_name, status, server_status, bill_amount,
              received_amount, discount_amount, doc, bill_number, lab_number,
              visible, created_by, created_at, last_updated_by, last_updated_at,
              sync_window
            FROM data.hc_patient_visit_detail
            WHERE tenant_id::text = bucket.tenant_id
              AND visible = true
              AND status = 'Finished'
              AND server_status = 'Received'
              AND sync_window = true


client_auth:
  jwks:
    keys:
      - kty: 'RSA'
        n: 'uIyEmd0HNaIqZXxFCXFNGxCH-pwH2D871IBlfdwuEGT2FoIjFlmgCWAWjFeHqy-FLddAy6q0AAMYQ3vsHMM6k4_14HalRy8byxQxEQK3Pq4Ua79zc4WLqQcDsCRfbEd5FD2O3NIk7nKHpJ3wKRk8fMcuMUfNEhNlEMfQzqTgiLUpG5CfDbfRGeBndG3pXF63iqZ1rZbVdkrMncCDkqS2MMxua7T98tdi_6nqYXQzCV-QFHRkOD7mx0K8zHYPR5psn1m_8xdIa_IJxYGo6JiYWtZB-gbqbU5AfI5uKqVppdEqfmFt2yb7pT5zMl5BOexJmgRWB6oTBNFmzSnkQXLMyw'
        e: 'AQAB'
        alg: 'RS256'
        kid: 'powersync-963d4c3800'
  audience: ['https://livesync.andrsn.in']

telemetry:
  disable_telemetry_sharing: true
